image: java:latest

stages:
  - build
  - deploy-dev2

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo "Building Jar File"
    - mvn clean package -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true
  artifacts:
    paths:
      - gwas-ui.jar
    expire_in: 1 day

deploy-dev1:
  stage: deploy-dev1
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no gwas-ui.jar $SNOOPY_SERVER:$DEV1_APP_DIRECTORY
    - ssh -o StrictHostKeyChecking=no $SNOOPY_SERVER
      "kill -9 \$(ps aux | grep 'gwas-ui.jar' | grep -v 'grep' | awk '{print \$2}');"
    - ssh -o StrictHostKeyChecking=no $SNOOPY_SERVER
      "cd $DEV1_APP_DIRECTORY; nohup java -jar gwas-ui.jar $PROGRAM_ARGUMENTS --spring.profiles.active=dev2 < /dev/null > $DEV1_APP_DIRECTORY/logs/gwas-ui.out 2>&1 &"
  only:
    - march-2021-refactoring


deploy-dev2:
  stage: deploy-dev2
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no gwas-ui.jar $SNOOPY_SERVER:$DEV2_APP_DIRECTORY
    - ssh -o StrictHostKeyChecking=no $SNOOPY_SERVER
      "kill -9 \$(ps aux | grep 'gwas-ui.jar' | grep -v 'grep' | awk '{print \$2}');"
    - ssh -o StrictHostKeyChecking=no $SNOOPY_SERVER
      "cd $DEV2_APP_DIRECTORY; nohup java -jar gwas-ui.jar $PROGRAM_ARGUMENTS --spring.profiles.active=dev2 < /dev/null > $DEV2_APP_DIRECTORY/logs/gwas-ui.out 2>&1 &"
  only:
    - dev