image: java:latest

stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo "Building Jar File"
    - mvn clean package -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true
  artifacts:
    paths:
      - gwas-ui.jar
    expire_in: 1 day

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no gwas-ui.jar $SNOOPY_SERVER:/homes/spotbot
    - ssh -o StrictHostKeyChecking=no $SNOOPY_SERVER
      "kill -9 \$(ps aux | grep 'gwas-ui.jar' | grep -v 'grep' | awk '{print \$2}');"
    - ssh -o StrictHostKeyChecking=no $SNOOPY_SERVER
      "cd /homes/spotbot; nohup java -jar gwas-ui.jar $PROGRAM_ARGUMENTS < /dev/null > /homes/spotbot/logs/gwas-ui.out 2>&1 &"
  only:
    - march-2021-refactoring

