
matrix:
  include:
    - language: node_js
      node_js: 10

      addons:
        sonarcloud:
          organization: "gwas-ebi"

      script:
        - sonar-scanner -Dsonar.organization=gwas-ebi -Dsonar.projectKey=gwas-ui -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=0566d66d0cfe16cd2cb8ba02db7fcd0b6d1e7ee6 -Dsonar.exclusions=**/*.java,**/target/**

    - language: java
      sudo: false
      jdk: openjdk11

      dist: trusty

      env:
        global:
        - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"
      addons:
        sonarcloud:
          organization: "gwas-ebi"

      script:
        - jdk_switcher use openjdk8
        - mvn clean verify -Dmaven.test.failure.ignore=true -Dmaven.test.error.ignore=true
        - export JAVA_HOME=$HOME/openjdk11
        - mvn sonar:sonar -Dsonar.login=0566d66d0cfe16cd2cb8ba02db7fcd0b6d1e7ee6

