language: java
sudo: false
jdk:
- openjdk8

env:
  global:
  - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"
addons:
  sonarcloud:
    organization: "gwas-ebi"

script:
- mvn clean verify sonar:sonar -Dmaven.test.failure.ignore=true -Dmaven.test.error.ignore=true -Dsonar.login=0566d66d0cfe16cd2cb8ba02db7fcd0b6d1e7ee6
