= Recommendations for authors

== Recommendations for authors reporting sample metadata in publications 

_Our recommendations are currently under review and we refer authors to the link:https://nap.nationalacademies.org/catalog/26902/using-population-descriptors-in-genetics-and-genomics-research-a-new[National Academy of Science, Engineering and Medicine report on the Use of Population Descriptors in Genomics 2023] for further guidelines on best practice. We here use the term “ancestry”, as is common in the field of human genomics, to describe a group of individuals who are either demonstrated or inferred to have shared genetic similarity relative to individuals sampled elsewhere in the world. We note that ancestry or genealogy per se is complex and typically has not been analysed in the majority of cases._

In order to facilitate harmonisation, comparison and monitoring across samples by users of the GWAS Catalog and to facilitate downstream use of the data, we recommend that authors adhere to the following recommendations, which are based on a detailed review of all GWAS publications included in the Catalog (3,200, as of February 2018) by expert curators, and were published in Morales et al. 2018, link:https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1396-2[A standardized framework for representation of ancestry data in genomics studies, with application to the NHGRI-EBI GWAS Catalog]:

1. Provide detailed information for each distinct group of samples

a. Ancestry descriptors should be as granular as possible (e.g. Yoruban instead of Sub-Saharan African, Japanese instead of Asian).

b. Avoid using country or citizenship as a substitute for genetic ancestry.

c. Avoid using geographic descriptors that are part of a cohort name as a substitute for ancestry (e.g. TwinsUK cannot be assumed to be European ancestry).

d. If a population self-identifies using sociocultural descriptors, clearly provide information about the underlying genetics or genealogy (e.g. Old Order Amish individuals of European descent)

e. If samples were derived from an isolated or founder population with limited genetic heterogeneity, clearly state the genetic ancestry within which this sub-population falls.

f. Every effort should be made to explicitly note whether the population is admixed and the ancestral backgrounds that contribute to admixture.

g. If available, genetic genealogy or ancestry of grandparents or parents should be included.

2. Report the method used to determine the ancestry of participants (for example, self-reported, inferred by genomic methods or a combination of both)

a.	Where possible, use genomic methods to infer the genetic ancestry of samples or to confirm self-reported ancestry.

b.	If genomic methods are used, indicate the analytical procedure utilized.  

3.	For harmonisation & interoperability purposes, assign an ancestry category label for each relevant group of samples. See link:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5815218/table/Tab1/?report=objectonly[Table 1] (Morales et al 2018), for a list and definition of labels. Refer to link:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5815218/bin/13059_2018_1396_MOESM3_ESM.xlsx[Table S2] (Morales et al 2018) for a list of descriptors in use in the Catalog with their category assignments.

4.	Provide the sample size for each distinct group of samples included in the analysis.

5.	Provide country of recruitment.

6.	If genetic ancestry information is not available due to confidentiality, or any other concerns, note this in the publication.
