= Downloading the GWAS Diagram
 
== Downloading the GWAS Diagram

To obtain an image of the GWAS Diagram, you are recommended to navigate to your view of interest and take a screenshot. 

Diagrams representing earlier stages of the Catalog are available from our FTP site in link:http://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/png[png], link:http://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/svg[svg] and link:http://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/pdf[pdf] formats! 

In the Diagram associations with p-values less than 5x10^-8^ are shown, and colored according to trait categories. See link:http://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/diagram_legend.png[legend] for details. An link:http://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_annotated_diagram_2025.pdf[annotated version of the diagram] is also available, containing the legend and additional details.

The GWAS Diagram, logos and other data visualisations are available for re-use under CC-BY-4.0. Please cite our https://www.ebi.ac.uk/gwas/docs/about[latest resource update paper]. 

== Slideshow

Diagrams from from each quarter since 2005 have been compiled into a visually striking time lapse:

video::/gwas/video/GWAS_Catalog_slideshow.mp4[width=800, height=460 ]

The slideshow can be downloaded in link:http://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_slideshow.mp4[mp4], link:http://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_slideshow.webm[webm], link:http://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_slideshow.ogg[ogg] and link:http://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_slideshow.pdf[pdf] formats.
