==== Summary statistics

==== Summary statistics acquisition

From 2017 the GWAS Catalog started hosting summary statistics files in addition to curated associations. Summary statistics are acquired from a number of different sources:

* Included in a curated paper as a supplementary file
* Identified via link or reference in a curated paper
* Identified via a consortium or author website
* Submitted to the GWAS Catalog by an author

==== Summary statistics eligibility

Summary statistics must meet a number of criteria to be eligible for inclusion in the Catalog:

* Must include >100,000 SNPs
* Must reproduce the initial GWAS extracted in the Catalog, i.e. same samples (not a sub-set, e.g. one cohort of a meta-analysis), and on the same trait
* Must be freely available, i.e. not only by request to author or password-protected
* Must not require agreement to any specific terms and conditions, unless this has been agreed in advance by the author/consortium

==== Summary statistics harmonisation

==== Summary statistics database 
