==== Summary statistics

==== Summary statistics acquisition

From 2017 the GWAS Catalog started hosting summary statistics files in addition to curated associations. Summary statistics are acquired from a number of different sources:

* Included in a curated paper as a supplementary file
* Identified via link or reference in a curated paper
* Identified via a consortium or author website
* Submitted to the GWAS Catalog by an author

We urge authors of GWAS publications included in the Catalog to contact us if summary statistics are available. If you wish to deposit summary statistics in the GWAS Catalog, please contact us via gwas-info@ebi.ac.uk for instructions on how to access our ftp server. We can then make these available through the Catalog. We can only include data in the Catalog that has been published in a peer-reviewed journal and indexed in PubMed. We aren’t currently able to provide accession numbers before publication. If you have an accepted publication for which you intend to submit summary statistics to the GWAS Catalog, and need to include a data availability statement in your manuscript, please contact us. Note that for summary statistics to be made available through the GWAS Catalog, your study must fulfil our eligibility criteria.

==== Summary statistics eligibility

Summary statistics must meet a number of criteria to be eligible for inclusion in the Catalog:

* Must include >100,000 SNPs
* Must reproduce the initial GWAS extracted in the Catalog, i.e. same samples (not a sub-set, e.g. one cohort of a meta-analysis), and on the same trait
* Must be freely available, i.e. not only by request to author or password-protected
* Must not require agreement to any specific terms and conditions, unless this has been agreed in advance by the author/consortium

==== Summary statistics harmonisation

==== Summary statistics database 

We are currently developing a database of GWAS summary statistics. The REST API for the summary statistics database is now available at www.ebi.ac.uk/gwas/docs/api/summary-statistics.
