= Submission

== How to submit

Authors of GWAS publications can now submit full p-value summary statistics using our https://www.ebi.ac.uk/gwas/deposition[submission interface] through the following steps:

1. <<link-1, Log in>>
2. <<link-2, Find publication>>
3. <<link-3, Create a submission>>
4. <<link-4, Submit>>

=== [[link-1]]1. Log in to the submission page

To get started, click LOGIN in the top right corner of the submission page.

Log in using your ELIXIR identity, or follow the link to register. Your ELIXIR identity may be linked to Google, LinkedIn, ORCID or an institutional account.

=== [[link-2]]2. Find publication

On the GWAS Catalog Submission page, you can find any publication that is included in the GWAS Catalog, or that has been identified by curators as eligible for inclusion.  You can search for a publication by *PubMed ID* or *first author*. Publications matching your search are displayed in the table.

==== What if my publication is not in the table?

A publication will not appear in the table if:

* it has not yet been indexed in PubMed
* it has been missed by our literature search, or
* curators have reviewed the publication and found that it does not meet our eligibility criteria

If you think that we are missing an eligible publication, or if you want to submit data that is not yet published, please contact us at gwas-info@ebi.ac.uk to request an eligibility review.

=== [[link-3]]3. Create a submission

Once you have found your publication on the https://www.ebi.ac.uk/gwas/deposition[submission page] click on the "PubMedID" and then "Create Submission" to create a submission.

==== What can I submit?

The “Status” column in the search results lets you know what you can submit for a particular publication:

[cols="<2,<1,<6,<1,<2", options="header", grid="all", width=100%]
|===
|Status
|
|Description
|
|What to submit

|OPEN FOR SUMMARY STATISTICS SUBMISSION
|
|The publication has been curated and the publication metadata is available on the GWAS Catalog website, but we don't have summary statistics yet.
|
|link:summary-statistics[Summary statistics only]

|OPEN FOR SUBMISSION
|
|The publication has been identified by curators and meets the GWAS Catalog’s inclusion criteria, but has not yet been curated. We don't have metadata or summary statistics yet.
|
|link:summary-statistics-plus-metadata[Summary statistics plus study metadata]
  
|CLOSED
|
|We are not currently accepting submissions for this publication. We either have the summary statistics already, or the publication is under submission by another author or curator. You may want to check with your co-authors, or contact us at gwas-info@ebi.ac.uk for more information.
|
|NA
|===

You can find instructions on how to create submissions of summary statistics only or summary statistics plus metadata through links in the table above.

=== [[link-4]]4. Submit

Once you have completed your submission click "Submit" to send the submission to the GWAS Catalog. You will be returned to the My Submissions page, where you can see your latest submission at the top, with the status SUBMITTED.

A curator will review your submission and make the summary statistics available to the public as soon as possible through the GWAS Catalog website.

== Additional Information

=== Viewing my Submissions

The My Submissions page displays all of your submissions. You can view old submissions or review and return to active submissions at any time. The table can be searched by PubMed ID or Submission ID.

=== [[checksums]] Calculating checksums for summary statistics files

In order to ensure the integrity of the uploaded summary statistics files before and after the upload, you must provide an md5 checksum (a kind of “fingerprint”) for each uploaded file. If there is any problem during the upload that leads to corruption of the data, this checksum will change. So by validating against the provided checksum, we can ensure the upload was successful and the data is not corrupted. Although there are various ways to calculate checksums, we are only supporting the most widely used md5 algorithm.

==== Calculating on Mac computers

+++ <details><summary> +++
+++ </summary><div> +++

The md5 command line application is installed on Mac computers by default. Type the following into the command line, replacing “summary_stats.gzip” with the name of your own file:

  $ md5 summary_stats.gzip

The output should look something like this:
  
  MD5 (summary_stats.gzip) = 49ea8cf53801c7f1e2f11336fb8a29c8

The md5 checksum is the 32-digit hexadecimal number in the output, after the filename. Copy this number into the corresponding column of the study sheet.

+++ </div></details> +++

==== Calculating on Linux/Unix computers

+++ <details><summary> +++
+++ </summary><div> +++

The md5sum command line application is installed on all Linux/Unix based systems by default. Type the following into the command line, replacing “summary_stats.gzip” with the name of your own file:

  $ md5sum summary_stats.gzip

The output should look something like this:

  4ab6d4f4db143eed49c248d3ce23cb57  summary_stats.gzip

The md5 checksum is the 32-digit hexadecimal number in the first column of the output, before the file name. Copy this number into the corresponding column of the study sheet.

+++ </div></details> +++

==== Calculating on Windows computers

+++ <details><summary> +++
+++ </summary><div> +++

In Windows, you can use the certutil command line tool to calculate md5 checksums. Type the following into the command line, replacing “summary_stats.gzip” with the name of your own file:

  > certutil -hashfile summary_stats.gzip MD5

The output should look something like this:

  ...

The md5 checksum is the 32-digit hexadecimal number provided by the application. Copy this number into the corresponding column of the study sheet.

+++ </div></details> +++
