= Submission

== How to submit

Authors of GWAS publications can now submit full summary statistics following the steps below:

1. <<link-1, Log in>>
2. <<link-2, Find publication>>
3. <<link-3, Check publication status>>
4. <<link-4, Set up Globus account for file transfer>>
4. <<link-4, Create a submission>>
5. <<link-5, Submit>>

=== [[link-1]]1. Log in to the submission page

First, open the https://www.ebi.ac.uk/gwas/deposition[GWAS Catalog Submission page^].

To get started, click LOGIN in the top right corner of the submission page.

Log in using your ELIXIR identity, or follow the link to register. Your ELIXIR identity may be linked to Google, LinkedIn, ORCID or an institutional account.

=== [[link-2]]2. Find publication

On the GWAS Catalog Submission page, you can find any publication that is included in the GWAS Catalog, or that has been identified by curators as eligible for inclusion.

You can search for a publication by *PubMed ID* or *first author*. Publications matching your search are displayed in the table.

==== What if my publication is not in the table?

A publication will not appear in the table if:

* it has not yet been indexed in PubMed
* it has been missed by our literature search, or
* curators have reviewed the publication and found that it does not meet our eligibility criteria

If you think that we are missing an eligible publication, or if you want to submit data that is not yet published, please contact us at gwas-info@ebi.ac.uk to request an eligibility review.

=== [[link-3]]3. Check publication status

Once you have found your publication, please take note of the Status. This will tell you which data to submit.

[cols="<2,<1,<6", options="header", grid="all", width=100%]
|===
|Status
|
|Instructions

|OPEN FOR SUMMARY STATISTICS SUBMISSION
|
|The publication has been curated and the publication metadata is already available on the GWAS Catalog website. Please submit *summary statistics only*.

|OPEN FOR SUBMISSION
|
|The publication meets the GWAS Catalog’s inclusion criteria, but has not yet been curated. Please submit *summary statistics plus study metadata*.
  
|CLOSED
|
|We are not currently accepting submissions for this publication. We either have the summary statistics already, or the publication is under submission by another author or curator. You may want to check with your co-authors, or contact us at gwas-info@ebi.ac.uk for more information.
|===

=== [[link-4]]4. Set up a Globus account



=== [[link-5]]5. Create submission

Click on the "PubMedID" for your publication and then click "Create Submission".

Then follow the instructions in the links below to:

1. https://www.ebi.ac.uk/gwas/docs/submission-summary-statistics[Submit summary statistics only^], or

2. https://www.ebi.ac.uk/gwas/docs/submission-summary-statistics-plus-metadata[Submit summary statistics plus study metadata^]

=== [[link-5]]5. Submit

Once you have completed your submission click "Submit" to send the submission to the GWAS Catalog. You will be returned to the My Submissions page, where you can see your latest submission at the top, with the status SUBMITTED.

A curator will review your submission and make the summary statistics available to the public as soon as possible through the GWAS Catalog website.

== Additional Information

=== Viewing my Submissions

The My Submissions page displays all of your submissions. You can view old submissions or review and return to active submissions at any time. The table can be searched by PubMed ID or Submission ID.
