= Downloading the GWAS Diagram
 
== Downloading the GWAS Diagram

Download the latest version of the iconic GWAS diagram in link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_diagram.svg[svg], link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_diagram.png[png] or in link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_diagram.pdf[pdf] formats. In the diagram associations with p-values less than 5x10^-8^ are shown, and colored according to trait categories. See link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/diagram_legend.png[legend] for details.

Diagrams representing earlier stages of the catalog are also available from our FTP site in link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/png[png], link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/svg[svg] and link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/pdf[pdf] formats! 

An link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_annotated_diagram.pdf[annotated version of the diagram] is also available containing legend and association counts in the  most recent release.

== Slideshow

Diagrams from from each quarter since 2005 have been compiled into a visually striking time lapse:

video::/gwas/video/GWAS_Catalog_slideshow.mp4[width=800, height=460 ]

The slideshow can be downloaded in link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_slideshow.mp4[mp4], link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_slideshow.webm[webm], link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_slideshow.ogg[ogg] and link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/timeseries/current/GWAS_Catalog_slideshow.pdf[pdf] formats.
